package Part_1_IntroductionInJava.Task_1_operation;
//import Part_1_IntroductionWithJava.MassivAndCycleForEachLessonByJava.Task_1_Primitives;
//import Part_1_IntroductionWithJava.MassivAndCycleForEachLessonByJava.Task_1_Primitives.Primitives;

public class Main {
    public static void main(String[] args) {
//        Part_1_IntroductionWithJava.MassivAndCycleForEachLessonByJava.Task_1_Primitives;
//        Primitives;
        int intNumber1 = 1313131313;
        int intNumber2 = 131;
        long longNumber1 = 1313131313131313131L;
        long longNumber2 = 1313L;
        byte byteNumber1 = 13;
        byte byteNumber2 = 15;
        short shortNumber1 = 2;
        short shortNumber2 = 25;
        float floatNumber1 = 13.13f;
        float floatNumber2 = 131.31f;
        double doubleNumber1 = 13.131313d;
        double doubleNumber2 = 131.3131313d;
        System.out.println("Сложение 1 Int:");
        int sumInt = intNumber1 + intNumber2;
        System.out.println(intNumber1 + " + " + intNumber2 + " = " + sumInt);
        long sumIntLong = (long)intNumber1 + longNumber1;
        System.out.println((long)intNumber1 + " + " + longNumber1 + " = " + sumIntLong);
        int sunIntByte = intNumber1 + (int) byteNumber1;
        System.out.println(intNumber1 + " + " + (int) byteNumber1 + " " + sunIntByte);
        int sumIntShort = intNumber1 + (int) shortNumber1;
        System.out.println(intNumber1 + " + " + (int) shortNumber1 + " = " + sumIntShort);
        float sumIntFloat = (float) intNumber2 + floatNumber2;
        System.out.println(intNumber2 + " + " + floatNumber2 + " = " + sumIntFloat);
        double sumIntDouble = (double) intNumber1 + doubleNumber1;
        System.out.println(intNumber1 + " + " + doubleNumber1 + " = " + sumIntDouble);
        System.out.println("Вычитание 1 Int:");
        int subtractionInt21 = intNumber2 - intNumber1;
        System.out.println(intNumber2 + " - " + intNumber1 + " = " + subtractionInt21);
        int subtractionInt12 = intNumber1 - intNumber2;
        System.out.println(intNumber1 + " - " + intNumber2 + " = " + subtractionInt12);
        long subtractionIntLong = (long) intNumber2 - longNumber2;
        System.out.println(intNumber2 + " - " + longNumber2 + " = " + subtractionIntLong);
        int subtractionIntByte = intNumber2 - (int) byteNumber2;
        System.out.println(intNumber2 + " - " + byteNumber2 + " = " + subtractionIntByte);
        int subtractionIntShort = intNumber2 - (int) shortNumber2;
        System.out.println(intNumber2 + " - " + shortNumber2 + " = " + subtractionIntShort);
        float subtractionIntFloat = intNumber1 - floatNumber1;
        System.out.println(intNumber1 + " - "  + floatNumber1 + " = " + subtractionIntFloat);
        double subtractionIntDouble = intNumber2 - doubleNumber2;
        System.out.println(intNumber2 + " " + doubleNumber2 + " = " + subtractionIntDouble);
        System.out.println("Умножение 1 Int:");
        long multiplicationInt = (long) intNumber1 * (long) intNumber2;
        System.out.println(intNumber1 + " * " + intNumber2 + " = " + multiplicationInt);
        long multiplicationIntLong = (long) intNumber1 * longNumber1;
        System.out.println(intNumber1 + " * " + longNumber1 + " = " + multiplicationIntLong);
        int multiplicationIntByte = intNumber1 * (int) byteNumber1;
        System.out.println(intNumber1 + " * " + byteNumber1 + " = " + multiplicationIntByte);
        int multiplicationIntShort = intNumber1 * (int) shortNumber1;
        System.out.println(intNumber1 + " * " + shortNumber1 + " = " + multiplicationIntShort);
        float multiplicationIntFloat = intNumber2 * floatNumber2;
        System.out.println(intNumber2 + " * " + floatNumber2 + " = " + multiplicationIntFloat);
        double multiplicationIntDouble = intNumber2 * doubleNumber2;
        System.out.println(intNumber2 + " * " + doubleNumber2 + " = " + multiplicationIntDouble);
        System.out.println("Деление 1 Int:");
        float divisionInt = (float) intNumber1 / (float) intNumber2;
        System.out.println(intNumber1 + " / " + intNumber2 + " = " + divisionInt);
        float divisionIntLong = (float) intNumber1 / (float) longNumber1;
        System.out.println(intNumber1 + " / " + longNumber1 + " = " + divisionIntLong);
        float divisionIntByte = (float) intNumber1 / (float) byteNumber1;
        System.out.println(intNumber1 + " / " + byteNumber1 + " = " + divisionIntByte);
        float divisionIntShort = (float) intNumber1 / shortNumber1;
        System.out.println(intNumber1 + " / " + shortNumber1 + " = " + divisionIntShort);
        float divisionIntFloat = intNumber2 / floatNumber2;
        System.out.println(intNumber2 + " / " + floatNumber2 + " = " + divisionIntFloat);
        double divisionIntDouble = intNumber2 / doubleNumber2;
        System.out.println(intNumber2 + " / " + doubleNumber2 + " = " + divisionIntDouble);
        System.out.println("Операция Получения Остатка Int 1:");
        int remainderInt = intNumber1 % intNumber2;
        System.out.println(intNumber1 + " % " + intNumber2 + " = " + remainderInt);
        int remainderIntLong = intNumber1 % (int) longNumber1;
        System.out.println(intNumber1 + " % " + longNumber1 + " = " + remainderIntLong);
        int remainderIntByte = intNumber1 % (int) byteNumber1;
        System.out.println(intNumber1 + " % " + byteNumber1 + " = " + remainderIntByte);
        int remainderIntShort = intNumber1 % shortNumber1;
        System.out.println(intNumber1 + " % " + shortNumber1 + " = " + remainderIntShort);
        int remainderIntFloat = intNumber2 % (int) floatNumber2;
        System.out.println(intNumber2 + " % " + floatNumber2 + " = " + remainderIntFloat);
        double remainderIntDouble =(double) intNumber2 % doubleNumber2;
        System.out.println(intNumber2 + " % " + doubleNumber2 + " = " + remainderIntDouble);


        System.out.println("Сложение 2 Long:");
        long sumLong = longNumber1 + longNumber2;
        System.out.println(longNumber1 + " + " + longNumber2 + " = " + sumLong);
        long sumLongInt = longNumber2 + intNumber2;
        System.out.println(longNumber2 + " + " + intNumber2 + " = " + sumLongInt);
        long sumLongByte = longNumber1 + (long) byteNumber1;
        System.out.println(longNumber1 + " + " + byteNumber1 + " = " + sumLongByte);
        long sumLongShort = longNumber1 + (long) shortNumber1;
        System.out.println(longNumber1 + " + " + shortNumber1 + " = " + sumLongShort);
        long sumLongFloat =  longNumber2 + (long) floatNumber2;
        System.out.println(longNumber2 + " + " + floatNumber2 + " = " + sumLongFloat);
        long sumLongDouble = longNumber1 + (long) doubleNumber1;
        System.out.println(longNumber2 + " + " + doubleNumber1 + " = " + sumLongDouble);
        System.out.println("Вычитание 2 Long:");
        long subtractionLong = longNumber2 - longNumber1;
        System.out.println(longNumber2 + " - " + longNumber1 + " = " + subtractionLong);
        long subtractionLongInt = longNumber2 - intNumber2;
        System.out.println(longNumber2 + " - " + intNumber2 + " = " + subtractionLongInt);
        long subtractionLongByte = longNumber2 - (long) byteNumber2;
        System.out.println(longNumber2 + " - " + byteNumber2 + " = " + subtractionLongByte);
        long subtractionLongShort = longNumber2 - (long) shortNumber2;
        System.out.println(longNumber2 + " - " + shortNumber2 + " = " + subtractionLongShort);
        long subtractionLongFloat = (long) (longNumber1 - (float) floatNumber1);
        System.out.println(longNumber1 + " - " + floatNumber1 + " = " + subtractionLongFloat);
        double subtractionLongDouble = (double) longNumber2 - doubleNumber2;
        System.out.println(longNumber2 + " - " + doubleNumber2 + " = " + subtractionLongDouble);
        System.out.println("Умножение 2 Long:");
        long multiplicationLong = longNumber1 * longNumber2;
        System.out.println(longNumber1 + " * " +  longNumber2 + " = " + multiplicationLong);
        long multiplicationLongInt = longNumber2 + (long) intNumber2;
        System.out.println(longNumber2 + " * " + intNumber2 + " = " + multiplicationLongInt);
        long multiplicationLongByte = longNumber1 * (long) byteNumber1;
        System.out.println(longNumber1 + " * " + byteNumber1 + " = " + multiplicationLongByte);
        long multiplicationLongShort = longNumber1 * (long) shortNumber1;
        System.out.println(longNumber1 + " * " + shortNumber1 + " = " + multiplicationLongShort);
        float multiplicationLongFloat = (float) longNumber2 * floatNumber2;
        System.out.println(longNumber2 + " * " + floatNumber2 + " = " + multiplicationLongFloat);
        double multiplicationLongDouble = longNumber2 * doubleNumber2;
        System.out.println(longNumber2 + " * " + doubleNumber2 + " = " + multiplicationLongDouble);
        System.out.println("Деление 2 Long:");
        long divisionLong = longNumber1 / longNumber2;
        System.out.println(longNumber1 + " / " + longNumber2 + " = " + divisionLong);
        long divisionLongInt = longNumber1 / (long) intNumber1;
        System.out.println(longNumber1 + " / " + intNumber1 + " = " + divisionLongInt);
        long divisionLongByte = longNumber1 / (long) byteNumber1;
        System.out.println(longNumber2 + " / " + byteNumber2 + " = " + divisionLongByte);
        long divisionLongShort = longNumber1 / (long) shortNumber1;
        System.out.println(longNumber1 + " / " + shortNumber1 + " = " + divisionLongShort);
        float divisionLongFloat = (float) longNumber2 / floatNumber2;
        System.out.println(longNumber2 + " / " + floatNumber2 + " = " + divisionLongFloat);
        double divisionLongDouble = longNumber2 / doubleNumber2;
        System.out.println(longNumber2 + " / " + doubleNumber2 + " = " + divisionLongDouble);
        System.out.println("Получение Остатка От Деления 2 Long: ");
        long remainderLong = longNumber2 % longNumber1;
        System.out.println(longNumber2 + " % " + longNumber1 + " = " + remainderLong);
        long remainderLongInt = longNumber2 % (long) intNumber2;
        System.out.println(longNumber2 + " % " + intNumber2 + " = " + remainderLongInt);
        long remainderLongByte = longNumber2 % (long) byteNumber2;
        System.out.println(longNumber2 + " % " + byteNumber2 + " = " + remainderLongByte);
        long remainderLongShort = longNumber2 % (long) shortNumber2;
        System.out.println(longNumber2 + " % " + shortNumber2 + " = " + remainderLongShort);
        float remainderLongFloat = longNumber1 % floatNumber1;
        System.out.println(longNumber1 + " % " + floatNumber1 + " = " + remainderLongFloat);
        double remainderLongDouble = (double) longNumber2 % doubleNumber2;
        System.out.println(longNumber2 + " % " + doubleNumber2 + " = " + remainderLongDouble);
        System.out.println("Суммироважние 3 Byte:");
        short sumByte = (short)(byteNumber1 + byteNumber2);
        System.out.println(intNumber1 + " + " + byteNumber2 + " = " + sumByte);
        int sumByteInt = (int) byteNumber2 + intNumber2;
        System.out.println(byteNumber2 + " * " + intNumber2 + " = " + sumByteInt);
        long sumByteLong = (long) byteNumber2 + longNumber2;
        System.out.println(byteNumber2 + " + " + longNumber2 + " = " + sumByteLong);
        int sumByteShort = (int) (byteNumber1 + shortNumber1);
        System.out.println(byteNumber1 + " + " + shortNumber1 + " = " + sumByteShort);
        float sumByteFloat = (float) byteNumber2 + floatNumber2;
        System.out.println(byteNumber2 + " + " + floatNumber2 + " = " + sumByteFloat);
        double sumByteDouble = (double) byteNumber2 + doubleNumber2;
        System.out.println(byteNumber2 + " + " + doubleNumber2 + " = " + sumByteDouble);
        System.out.println("Вычитание 3 Byte:");
        byte subtractionByte = (byte) (byteNumber2 - byteNumber1);
        System.out.println(byteNumber2 + " - " + byteNumber1 + " = " + subtractionByte);
        int subtractionByteInt = (int) byteNumber2 - intNumber2;
        System.out.println(byteNumber2 + " - " + intNumber2 + " = " + subtractionByteInt);
        long subtractionByteLong = (long) byteNumber1 - longNumber1;
        System.out.println(byteNumber1 + " - " + longNumber1 + " = " + subtractionByteLong);
        short subtractionByteShort = (short) (byteNumber2 - shortNumber2);
        System.out.println(byteNumber2 + " - " + shortNumber2 + " = " + subtractionByteShort);
        float subtractionByteFloat = byteNumber2 - floatNumber2;
        System.out.println(byteNumber2 + " - " + floatNumber2 + " = " + subtractionByteFloat);
        double subtractionByteDouble = byteNumber1 - doubleNumber1;
        System.out.println(byteNumber1 + " - " + doubleNumber1 + " = " + subtractionByteDouble);
        System.out.println("Умножение 3 Byte:");
        short multiplicationByte = (short) (byteNumber1 * byteNumber2);
        System.out.println(byteNumber1 + " * " + byteNumber2 + " = " + multiplicationByte);
        int multiplicationByteInt = (int) byteNumber2 * intNumber2;
        System.out.println(byteNumber2 + " * " + intNumber1 + " = " + multiplicationByteInt);
        long multiplicationByteLong = (long) byteNumber2 * longNumber2;
        System.out.println(byteNumber1 + " * " + longNumber1 + " = " + multiplicationByteLong);
        short multiplicationByteShort = (short) (byteNumber2 * shortNumber2);
        System.out.println(byteNumber2 + " * " + shortNumber2 + " = " + multiplicationByteShort);
        float multiplicationByteFloat = (float) ((float)byteNumber2 * floatNumber2);
        System.out.println(byteNumber2 + " * " + floatNumber2 + " = " + multiplicationByteFloat);
        double multiplicationByteDouble = (double) byteNumber1 * doubleNumber1;
        System.out.println(byteNumber1 + " * " + doubleNumber1 + " = " + multiplicationByteDouble);
        System.out.println("Деление 3 Byte:");
        float divisionByte = (float) byteNumber2 / (float) byteNumber1;
        System.out.println(byteNumber2 + " / " + byteNumber1 + " = " + divisionByte);
        float divisionByteInt = (float) byteNumber2 / (float) intNumber2;
        System.out.println(byteNumber2 + " / " + intNumber2 + " = " + divisionByteInt);
        float divisionByteLong = (float) byteNumber2 / (float) longNumber2;
        System.out.println(byteNumber2 + " / " + longNumber2 + " = " + multiplicationByteLong);
        float divisionByteShort = (float) byteNumber1 / (float) shortNumber1;
        System.out.println(byteNumber1 + " / " + shortNumber1 + " = " + divisionByteShort);
        float divisionByteFloat = (float) byteNumber1 / floatNumber1;
        System.out.println(byteNumber1 + " / " + floatNumber1 + " = " + divisionByteFloat);
        double divisionByteDouble = (double) byteNumber1 / doubleNumber1;
        System.out.println(byteNumber1 + " / " + doubleNumber1 + " = " + divisionByteDouble);
        System.out.println("Получение Остатка 3 Byte:");
        int remainderByte = (int) byteNumber2 % (int) byteNumber1;
        System.out.println(byteNumber2 + " % " + byteNumber2 + " = " + remainderByte);
        int remainderByteInt = (int) byteNumber2 % intNumber2;
        System.out.println(byteNumber2 + " % " + intNumber2 + " = " + remainderByteInt);
        int remainderByteLong = (int) byteNumber1 % (int) longNumber2;
        System.out.println(byteNumber1 + " % " + longNumber1 + " = " + remainderByteLong);
        int remainderByteShort = (int) byteNumber2 % (int) shortNumber2;
        System.out.println(byteNumber2 + " % " + shortNumber2 + " = " + remainderByteShort);
        float remainderByteFloat = (float) ((float) byteNumber1 % floatNumber1);
        System.out.println(byteNumber1 + " % " + floatNumber1 + " = " + remainderByteFloat);
        double remainderByteDouble = (double) ((double) byteNumber1 % doubleNumber1);
        System.out.println(byteNumber1 + " % " + doubleNumber1 + " = " + remainderByteDouble);
        System.out.println("Суммирование 4 short:");
        int sumShort = (int) shortNumber1 + (int) shortNumber2;
        System.out.println(shortNumber1 + " + " + shortNumber2 + " = " + sumShort);
        int sumShortInt = (int) shortNumber1 + intNumber1;
        System.out.println(shortNumber1 + " + " + intNumber1 + " = " + sumShortInt);
        int sumShortLong = (int) shortNumber2 + (int) longNumber2;
        System.out.println(shortNumber2 + " + " + longNumber2 + " = " + sumShortLong);
        int sumShortByte = (int) shortNumber1 + (int) byteNumber1;
        System.out.println(shortNumber1 + " + " + byteNumber1 + " = " + sumShortByte);
        float sumShortFloat = (float) shortNumber2 + floatNumber2;
        System.out.println(shortNumber2 + " + " + floatNumber2 + " = " + sumShortFloat);
        double subShortDouble = (double) shortNumber2 + doubleNumber2;
        System.out.println(shortNumber2 + " + " + doubleNumber2 + " = " + subShortDouble);
        System.out.println("Вычитание 4 short:");
        int subtractionShort = shortNumber2 - shortNumber1;
        System.out.println(shortNumber2 + " - " + shortNumber1 + " = " + subtractionShort);
        int subtractionShortInt = (int) shortNumber2 - intNumber2;
        System.out.println(shortNumber2 + " - " + intNumber2 + " = " + subtractionShortInt);
        long subtractionShortLong = (long) shortNumber1 - longNumber1;
        System.out.println(shortNumber1 + " - " + longNumber1 + " = " + subtractionShortLong);
        short subtractionShortByte = (short) (shortNumber1 - byteNumber1);
        System.out.println(shortNumber1 + " - " + byteNumber1 + " = " + subtractionShortByte);
        float subtractionShortFloat = (float) shortNumber2 - floatNumber2;
        System.out.println(shortNumber2 + " - " + floatNumber2 + " = " + subtractionShortFloat);
        double subtractionShortDouble = shortNumber2 - doubleNumber2;
        System.out.println(shortNumber2 + " - " + doubleNumber2 + " = " + subtractionShortDouble);
        System.out.println("Умножение 4 short");
        long multiplicationShort = (long) shortNumber1 * (long) shortNumber2;
        System.out.println(shortNumber1 + " * " + shortNumber2 + " = " + multiplicationShort);
        int multiplicationShortInt = (int) shortNumber1 * intNumber1;
        System.out.println(shortNumber1 + " * " + intNumber2 + " = " + multiplicationShortInt);
        long multiplicationShortLong = (long) shortNumber2 * longNumber2;
        System.out.println(shortNumber2 + " * " + longNumber2 + " = " + multiplicationShortLong);
        int multiplicationShortByte = (int) shortNumber1 * (int) byteNumber1;
        System.out.println(shortNumber1 + " * " + byteNumber1 + " = " + multiplicationShortByte);
        float multiplicationShortFloat = (float) shortNumber2 * floatNumber2;
        System.out.println(shortNumber1 + " * " + floatNumber2 + " = " + multiplicationShortFloat);
        double multiplicationShortDouble = (double) shortNumber1 * doubleNumber1;
        System.out.println(shortNumber1 + " * " + doubleNumber1 + " = " + multiplicationShortDouble);
        System.out.println("Деление 5 short:");
        float divisionShort = (float) shortNumber2 / (float) shortNumber1;
        System.out.println(shortNumber2 + " / " + shortNumber1 + " = " + divisionShort);
        float divisionShortInt = (float) shortNumber1 / (float) intNumber1;
        System.out.println(shortNumber1 + " / " + intNumber1 + " = " + divisionShortInt);
        float divisionShortLong = (float) shortNumber2 / (float) longNumber2;
        System.out.println(shortNumber2 + " / " + longNumber2 + " = " + divisionShortLong);
        float divisionShortByte = (float) shortNumber2 / (float) byteNumber2;
        System.out.println(shortNumber2 + " / " + byteNumber2 + " = " + divisionShortByte);
        float divisionShortFloat = (float) shortNumber1 / floatNumber1;
        System.out.println(shortNumber1 + " / " + floatNumber1 + " = " + divisionShortFloat);
        double divisionShortDouble = (double) shortNumber2 / doubleNumber2;
        System.out.println(shortNumber2 + " / " + doubleNumber2 + " = " +  divisionShortDouble);
        System.out.println("Получение Остатка От Деления 5 short");
        int remainderShort = shortNumber2 % shortNumber1;
        System.out.println(shortNumber2 + " % " + shortNumber1 + " = " + remainderShort);
        int remainderShortInt = (int) shortNumber2 % intNumber2;
        System.out.println(shortNumber2 + " " + intNumber2 + " = " + remainderShortInt);
        int remainderShortLong = (int) shortNumber1 % (int) longNumber1;
        System.out.println(shortNumber1 + " % " + longNumber1 + " = " + remainderShortLong);
        float remainderShortByte = (float) shortNumber2 % (float) byteNumber2;
        System.out.println(shortNumber2 + " % " + byteNumber2 + " = " + remainderShortByte);
        float remainderShortFloat = (float) shortNumber1 % floatNumber1;
        System.out.println(shortNumber1 + " % " + floatNumber1 + " = " + remainderShortFloat);
        double remainderShortDouble = (double) shortNumber2 % doubleNumber2;
        System.out.println(shortNumber2 + " % " + shortNumber2 + " = " + remainderShortDouble);
        System.out.println();
        System.out.println("Суммирование 6 float");
        float sumFloat = floatNumber1 + floatNumber2;
        System.out.println(floatNumber1 + " + " + floatNumber2 + " = " + sumFloat);
        float sumFloatInt = floatNumber2 + (float) intNumber2;
        System.out.println(floatNumber2 + " + " + intNumber2 + " = " + sumFloatInt);
        float sumFloatLong = floatNumber1 + (float) longNumber1;
        System.out.println(floatNumber1 + " + " + longNumber1 + " = " + sumFloatLong);
        float sumFloatByte = floatNumber1 + (float) byteNumber1;
        System.out.println(floatNumber1 + " + " + byteNumber1 + " = " + sumFloatByte);
        float sumFloatShort = floatNumber2 + (float) shortNumber2;
        System.out.println(floatNumber2 + " + " + shortNumber2 + " = " + sumFloatShort);
        float sumFloatDouble = floatNumber2 + (float) doubleNumber2;
        System.out.println(floatNumber2 + " + " + shortNumber2 + " = " + sumFloatDouble);
        System.out.println("Вычитание 6 float");
        float subtractionFloat = floatNumber2 - floatNumber1;
        System.out.println(floatNumber2 + " - " + floatNumber1 + " = " + subtractionFloat);
        float subtractionFloatInt = floatNumber1 - intNumber1;
        System.out.println(floatNumber1 + " - " + intNumber1 + " = " + subtractionFloatInt);
        float subtractionFloatLong = floatNumber2 - (float) intNumber2;
        System.out.println(floatNumber2 + " - " + intNumber2 + " = " + subtractionFloatLong);
        float subtractionFloatByte = floatNumber2 - (float) byteNumber2;
        System.out.println(floatNumber2 + " - " + byteNumber2 + " = " + subtractionFloatByte);
        float subtractionFloatShort = floatNumber1 - (float) shortNumber1;
        System.out.println(floatNumber1 + " - " + shortNumber1 + " = " + subtractionFloatShort);
        float subtractionFloatDouble = floatNumber2 - (float) doubleNumber2;
        System.out.println(floatNumber2 + " - " + doubleNumber2 + " = " + sumFloatDouble);
        System.out.println("Умножение 6 float");
        float multiplicationFloat = floatNumber1 * floatNumber2;
        System.out.println(floatNumber1 + " * " + floatNumber2 + " = " + multiplicationFloat);
        float multiplicationFloatInt = floatNumber2 * (float) intNumber2;
        System.out.println(floatNumber2 + " * " + intNumber2 + " = " + multiplicationFloatInt);
        float multiplicatiobFloatLong = floatNumber1 * (float) longNumber1;
        System.out.println(floatNumber1 + " * " + longNumber1 + " = " + multiplicatiobFloatLong);
        float multiplicationFloatByte = floatNumber2 * (float) byteNumber2;
        System.out.println(floatNumber2 + " * " + byteNumber2 + " = " + multiplicationFloatByte);
        float multiplicationFloatShort = floatNumber2 * (float) shortNumber2;
        System.out.println(floatNumber2 + " * " + shortNumber2 + " = " + multiplicationFloatShort);
        double multiplicationFloatDouble = (double) floatNumber1 * doubleNumber1;
        System.out.println((double) floatNumber1 + " * " + doubleNumber1 + " = " + multiplicationFloatDouble);
        System.out.println("Деление 6 float");
        float divisionFloat = floatNumber2 / floatNumber1;
        System.out.println(floatNumber2 + " / " + floatNumber1 + " = " + divisionFloat);
        float divisionFloatInt = floatNumber1 / intNumber1;
        System.out.println(floatNumber1 + " / " + (float) intNumber1 + " = " + divisionFloatInt);
        float divisionFloatLong = floatNumber1 / (float) longNumber1;
        System.out.println(floatNumber1 + " / " + longNumber1 + " = " + divisionFloatLong);
        float divisionFloatByte = floatNumber2 / (float) byteNumber2;
        System.out.println(floatNumber2 + "/" + byteNumber2 + " = " + divisionFloatByte);
        float divisionFloatShort = floatNumber2 / (float) shortNumber2;
        System.out.println(floatNumber2 + " / " + shortNumber2 + " = " + divisionFloatShort);
        double divisionFloatDouble = floatNumber1 / (float) doubleNumber1;
        System.out.println(floatNumber1 + " / " + shortNumber1 + " = " + divisionFloatDouble);
        System.out.println("Получение Остатка От Деления 6 Float");
        float remainderFloat = floatNumber1 % floatNumber2;
        System.out.println(floatNumber1 + " % " + floatNumber2 + " = " + remainderFloat);
        float remainderFloatInt = floatNumber2 % (float) intNumber2;
        System.out.println(floatNumber2 + " % " + intNumber2 + " = " +remainderFloatInt);
        float remainderFloatLong = floatNumber1 % (float) intNumber2;
        System.out.println(floatNumber1 + " % " + intNumber2 + " = " + remainderFloatLong);
        float remainderFloatByte = floatNumber2 % (float) byteNumber2;
        System.out.println(floatNumber2 + " % " + byteNumber2 + " = " + remainderFloatByte);
        float remainderFloatShort = floatNumber1 % (float) shortNumber1;
        System.out.println(floatNumber1 + " % " + shortNumber1 + " = " + remainderFloatShort);
        double remainderFloatDouble = (double) floatNumber1 % doubleNumber1;
        System.out.println(floatNumber1 + " % " + doubleNumber1 + " = " + remainderFloatDouble);






        System.out.println();
        System.out.println("Суммирование 7 double:");
        double sumDouble = doubleNumber1 + doubleNumber2;
        System.out.println(doubleNumber1 + " + " + doubleNumber2 + " = " + sumDouble);
        double sumDoubleInt = doubleNumber2 + (double) intNumber2;
        System.out.println(doubleNumber2 + " + " + intNumber2 + " = " + sumDoubleInt);
        double sumDoubleLong = doubleNumber2 + longNumber2;
        System.out.println(doubleNumber2 + " + " + longNumber2 + " = " + sumDoubleLong);
        double sumDoubleByte = doubleNumber2 + (byteNumber2);
        System.out.println(doubleNumber2 + " + " + byteNumber2 + " = " + sumDoubleByte);
        double sumDoubleShort = doubleNumber1 + shortNumber1;
        System.out.println(doubleNumber1 + " + " + shortNumber1 + " = " + sumDoubleShort);
        double sumDoubleFloat = doubleNumber1 + (double) floatNumber1;
        System.out.println(doubleNumber1 + " + " + floatNumber1 + " = " + sumDoubleFloat);







    }
}
